### ISSUE TITLE
Cloud factor using HRRR during night hours

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/basin_ops#1]
## Issue
The calculation for hourly cloud factor is incorrect for the nighttime hours. The assumption made is that cloud factor is equal to the HRRR solar input divided by the theoretical basin solar input, and can be set to 0 when there is no theoretical solar input. The assumption that it can be set to 0 is incorrect, as this means full cloud cover, and will increase the long-wave radiation at night.

## Effect
Increased long-wave radiation leads to higher snowpack temperatures and higher melt.

## Possible solution
Calculate the cloud factor only during the daytime hours, and then interpolate between days to fill in the night hours.

**Comment by micah-prime** [comment]
## Kings
This solution was implemented successfully in late March 2019 and is being tested in each operational basin to show the effects on various snow state variables including cold content, density, depth, and swe. All descriptions and figures include the fix for issues #1 and issues #2.

The fix shows about a 4% increase in SWE withihn the basin before any ASO depths were applied (up through 3/15/2019). This is thought to be mostly due to lower melt because of decreased incoming thermal radiation. The snowpack temperatures are also lower, meaning there is less snow available for melt (can be seen in the cold content image). 

The density is generally similar. The main difference in density seems to be caused by the location of the precipitation due to the local gradient fix from issue #2. 
 
![kings_20190315_swe_z](https://user-images.githubusercontent.com/32111103/55978804-f427d880-5c4d-11e9-909b-a420dd7357eb.png)
![kings_20190315_depth](https://user-images.githubusercontent.com/32111103/55978837-099d0280-5c4e-11e9-90c2-53459d219377.png)
![kings_20190315_coldcont](https://user-images.githubusercontent.com/32111103/55978879-25080d80-5c4e-11e9-8a8b-2c0ec2c99320.png)
![kings_20190315_density](https://user-images.githubusercontent.com/32111103/55978923-394c0a80-5c4e-11e9-8c11-eca9dd862bcb.png)

**Comment by micah-prime** [comment]
## Tuolumne

This solution was implemented successfully in late March 2019 and is being tested in each operational basin to show the effects on various snow state variables including cold content, density, depth, and swe. All descriptions and figures include the fix for issues #1 and issues #2.

The fix shows about a 3.7% increase in SWE withihn the basin before any ASO depths were applied (up through 3/23/2019). This is thought to be mostly due to lower melt because of decreased incoming thermal radiation. The snowpack temperatures are also lower, meaning there is less snow available for melt (can be seen in the cold content image). 

The density is generally similar. The main difference in density seems to be caused by the location of the precipitation due to the local gradient fix from issue #2. 

![tuolumne_20190323_swe_z](https://user-images.githubusercontent.com/32111103/55993072-65c24f80-5c6b-11e9-89c6-733c535baf29.png)
![tuolumne_20190323_depth](https://user-images.githubusercontent.com/32111103/55993076-6824a980-5c6b-11e9-8226-ba7ecf402ab0.png)
![tuolumne_20190323_coldcont](https://user-images.githubusercontent.com/32111103/55993082-6e1a8a80-5c6b-11e9-9781-84ad65a81b78.png)
![tuolumne_20190323_density](https://user-images.githubusercontent.com/32111103/55993095-75419880-5c6b-11e9-9c7b-e308921d7747.png)

**Comment by micah-prime** [comment]
## Lakes

The fix shows about a negligible change in SWE withihn the basin before any ASO depths were applied (up through 3/08/2019). The snowpack temperatures are also lower, meaning there is less snow available for melt (can be seen in the cold content image). 

The most drastic different is in the location of the SWE due to the local gradient fix from issue #2 and the result of removing the basin from the San Joaquin domain. The Lakes operates on a small enough scale that the changes are much easier to identify. 

![compare_swe_vol_lakes_wy2019_devel](https://user-images.githubusercontent.com/32111103/55994899-47ab1e00-5c70-11e9-93be-4deb9d32de26.png)
![lakes_20190308_swe_z](https://user-images.githubusercontent.com/32111103/55994904-4a0d7800-5c70-11e9-817a-b43a1c0ae139.png)
![lakes_20190308_depth](https://user-images.githubusercontent.com/32111103/55994908-4f6ac280-5c70-11e9-9f45-788bf8056367.png)
![lakes_20190308_coldcont](https://user-images.githubusercontent.com/32111103/55994909-51348600-5c70-11e9-8b53-12e169a263e5.png)
![lakes_20190308_density](https://user-images.githubusercontent.com/32111103/55994912-52fe4980-5c70-11e9-8793-e14a13499e08.png)

**Comment by scotthavens** [comment]
As @micah-prime mentioned, this was fixed in March 2019
