### ISSUE TITLE
Fix Tau and K errors in Topos 

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/basin_ops#4]
A bug in basin_setup ([basin_setup Issue #31](https://github.com/USDA-ARS-NWRC/basin_setup/issues/31)) resulted in 0's being used in places where parameters were undefined. That has been fixed but the topos still need updating with some documentation of that change which occur here.

**Comment by micahjohnson150** [comment]
@Hedrick-ARS , @scotthavens and @etrujil  have alook when you all get a chance. I will post more info next week.

**Changes to the Topos below** 

*Tuolumne*
![tuolumne_veg_k_topo_diff](https://user-images.githubusercontent.com/7646021/62806903-45878d80-bab1-11e9-88f3-c68074b54627.png)
![tuolumne_veg_tau_topo_diff](https://user-images.githubusercontent.com/7646021/62806906-47515100-bab1-11e9-9982-8a2fe2c38686.png)


*Merced* 
![merced_veg_k_topo_diff](https://user-images.githubusercontent.com/7646021/62806942-66e87980-bab1-11e9-85a9-196904e6031b.png)
![merced_veg_tau_topo_diff](https://user-images.githubusercontent.com/7646021/62806955-6e0f8780-bab1-11e9-8b14-c37e562f32cc.png)

*San Joaquin*
![sanjoaquin_veg_k_topo_diff](https://user-images.githubusercontent.com/7646021/62807051-a1eaad00-bab1-11e9-9f0e-cf9df0456012.png)

![sanjoaquin_veg_tau_topo_diff](https://user-images.githubusercontent.com/7646021/62807071-b333b980-bab1-11e9-841a-bef1b7725bf6.png)


*Lakes*
![lakes_veg_k_topo_diff](https://user-images.githubusercontent.com/7646021/62807091-c050a880-bab1-11e9-8b70-de4226bf04c9.png)
![lakes_veg_tau_topo_diff](https://user-images.githubusercontent.com/7646021/62807095-c2b30280-bab1-11e9-9d65-c1bf6ff6328c.png)


*Kings*
I had a cell mismatch in the kings I am looking into. So far its 5m off in the y. 


*Kaweah*

![kaweah_veg_k_topo_diff](https://user-images.githubusercontent.com/7646021/62808427-4c180400-bab5-11e9-9b5d-18ffdaeebfc1.png)

![kaweah_veg_tau_topo_diff](https://user-images.githubusercontent.com/7646021/62808432-4fab8b00-bab5-11e9-8dff-2626c5c7a719.png)


* Boise RIver Basin *
- Needs more veg class definitions
- This was an old topo so the flip up down will be seen in the change.

* RCEW * 
- Needs more veg class definitions
- This also was an older topo for us and thus the flip up down issue will be seen in the changes

**Comment by micahjohnson150** [comment]
Here is the kings: Note there is a 7x5m shift that I can't figure out how it changed. My best guess is that I made this with a different version of GDAL than the others and there was a minor change in how the -tap flag works (which helps with extents that don't fit the cell size perfectly), or it may have happened when veg was modified.

All the images are different in this one but I have not included all the masks as the story is the same. I included the difference on the whole mask for demonstration.

*Kings*
![kings_dem_topo_diff](https://user-images.githubusercontent.com/7646021/62952470-f4291800-bda8-11e9-8055-b59403ed4fde.png)
![kings_veg_k_topo_diff](https://user-images.githubusercontent.com/7646021/62952499-ff7c4380-bda8-11e9-842c-3fc680abe936.png)

![kings_mask_topo_diff](https://user-images.githubusercontent.com/7646021/62952493-fa1ef900-bda8-11e9-8a95-ace9ec67a22b.png)


![kings_veg_tau_topo_diff](https://user-images.githubusercontent.com/7646021/62952507-02773400-bda9-11e9-81b6-a005bda466a8.png)

**Comment by micahjohnson150** [comment]
For evaluation purposes this was requested last week during our meeting. I figured I would get this done so the new values could be assessed while I am working on config items.

![veg_type_histogram](https://user-images.githubusercontent.com/7646021/64214031-1bd14480-ce6c-11e9-9553-8f77c2e4faa3.png)

Here is the breakdown of all the values that break over 1% of the total topos pixel count:

VEG      Percent
3292     1.288462
3126     1.372445
3220     1.648736
3138     1.660005
3152     1.988333
3031     2.185774
3011     2.275699
3033     2.442632
3137     2.456243
3058     2.856024
3027     3.029738
3098     3.116680
3105     3.126759
3221     4.423736
3028     8.175912
3294    11.034236
3032    11.844274

**Comment by scotthavens** [comment]
![image](https://user-images.githubusercontent.com/7975741/64275442-c5631500-cf02-11e9-9481-a6a1a0e8ac18.png)

This table is what we are trying to classify to.

3032 - Mediterranean California Red Fir Forest, evergreen open tree canopy, tau=0.2, k=0.04
3294 - Barren, tau=1, k=0
3028 - Mediterranean California Mesic Mixed Conifer Forest and Woodland, evergreen closed canopy, tau=0.2, k=0.04
3221 - Mediterranean California Sparsely Vegetated Systems II, sparsely vegetated, tau=1, k=0
3105 - Northern and Central California Dry-Mesic Chaparral, evergreen shrubland, tau=1, k=0
3098 - California Montane Woodland and Chaparral, evergreen shrubland, tau=0.44, k=0.025
3027 - Mediterranean California Dry-Mesic Mixed Conifer Forest and Woodland, evergreen open canopy, tau=0.2, k=0.04
3058 - Sierra Nevada Subalpine Lodgepole Pine Forest and Woodland, evergreen closed canopy, tau=0.16, k=0.074
3137 - Mediterranean California Subalpine Meadow, grassland, tau=1, k=0
3033 - Mediterranean California Subalpine Woodland, evergreen open canopy, tau=0.2, k=0.04
3011 - Rocky Mountain Aspen Forest and Woodland, deciduous open canopy, tau=0.44, k=0.025
3031 - California Montane Jeffrey Pine(-Ponderosa Pine) Woodland, evergreen open canopy, tau=0.2, k=0.04
3152 - California Montane Riparian Systems, mixed open canopy, tau=0.2, k=0.04
3138 - North Pacific Montane Grassland, tau=1, k=0
3220 - Artemisia tridentata ssp. vaseyana Shrubland Alliance, big sagebrush, tau=1, k=0
3126 - Inter-Mountain Basins Montane Sagebrush Steppe, tau=1, k=0

**Comment by micahjohnson150** [comment]
@scotthavens these look like the same numbers, is that correct? Just making sure you didn't post any changes.

@etrujil, @Hedrick-ARS , @robertson-mark are any of these numbers of concern? Do we see any needs for altering them? I would love to merge these into the main branches of the repo and close this issue.

**Comment by scotthavens** [comment]
I didn't make any changes, just showing what those are set to so we can review it. There are a few in there that we might want to double check and make a decision on. I'm looking at 3098 which is evergreen shrubland but classified as deciduous.

**Comment by micahjohnson150** [comment]
I would like to add these as well, they represent some from the RME topo and I can't run them without adding them now. Here is my best guess on them using scott's info and the table as best I can.

3045 - Northern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest, Tree-dominated,Closed tree canopy , tau = 0.20 , k = 0.04

3055 - Rocky Mountain Subalpine Dry-Mesic Spruce-Fir Forest and Woodland, tree-dominated,Closed tree canopy, tau = 0.20 , k = 0.04

3123 - Columbia Plateau Steppe and Grassland, Shrub-dominated, tau = 1.0 , k = 0.0 
3139 - Northern Rocky Mountain Lower Montane-Foothill-Valley Grassland, herbaceous, tau = 1.0 , k = 0.0 

3140 - Northern Rocky Mountain Subalpine-Upper Montane Grassland, grassland, herbaceous, tau = 1.0, k = 0.0 

3159 - Rocky Mountain Montane Riparian Forest and Woodland, Open tree canopy, tree dominated, tau = 0.44 , k = 0.025

3227 - Dry-mesic Montane Douglas-fir Forest, open canopy, tree dominated, tau = 0.2, k = 0.04 

3232 - Abies grandis Forest Forest, Tree-dominated, Closed tree canopy, tau = 0.2, k = 0.04
